version: "3.3"
services:
  app:
    container_name: projects_crudservice_dev
    image: bsapaka/projects_crudservice_dev
    build:
      context: ../../
      dockerfile: ./docker/dev/Dockerfile
    environment:
      FLASK_APP: $FLASK_APP
      ENVIRONMENT: $ENVIRONMENT
      FLASK_DEBUG: 1
    volumes:
      - "../../:/var/app"
    ports:
      - $PORT:5000
    expose:
      - $PORT