"""empty message

Revision ID: 69eeb6e65b8e
Revises: 4e4007eacda5
Create Date: 2018-01-08 21:04:32.836540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69eeb6e65b8e'
down_revision = '4e4007eacda5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=True),
    sa.Column('short_summary', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contribution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('subtitle', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ability_contribution',
    sa.Column('ability_id', sa.Integer(), nullable=True),
    sa.Column('contribution_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ability_id'], ['ability.id'], ),
    sa.ForeignKeyConstraint(['contribution_id'], ['contribution.id'], )
    )
    op.create_table('contribution_skill',
    sa.Column('contribution_id', sa.Integer(), nullable=True),
    sa.Column('skill_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contribution_id'], ['contribution.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], )
    )
    op.drop_table('project')
    op.drop_table('project_skill')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_skill',
    sa.Column('project_id', sa.INTEGER(), nullable=True),
    sa.Column('skill_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], )
    )
    op.create_table('project',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('owner_id', sa.VARCHAR(), nullable=True),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('subtitle', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('contribution_skill')
    op.drop_table('ability_contribution')
    op.drop_table('contribution')
    op.drop_table('ability')
    # ### end Alembic commands ###
